collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.7674544
color:
  saturation: 0.7953813
  brandStrength: 1
  lightness: 0.3313641
  brandColors:
    - '#0B0601'
    - '#C8A472'
    - '#CFCDB4'
    - '#A9864F'
    - '#5D3C10'
  rhythmicContrast: 0.656514
layout_spectrum: 0.06283564
name: Milan Fine Art Collection
