layout_spectrum: 0.4059376392979175
typography_spectrum: 0.037072497652843595
color:
  brandStrength: 0.3683753605000675
  lightness: 0.584750437643379
  saturation: 0.09541846765205264
  rhythmicContrast: 0.461016594665125
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
name: Milan Fine Art Collection
