collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.1928034
  brandStrength: 0.9887217
  lightness: 0.5902256
  brandColors:
    - '#F0F0E8'
    - '#525252'
    - '#272121'
    - '#94846A'
    - '#9FAFBF'
  rhythmicContrast: 0.5204082
typography_spectrum: 0.9425349
layout_spectrum: 0.2518797
name: Milan Fine Art Collection
