collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.9505052901804447
  brandStrength: 0.5787233712617308
  lightness: 0.4824135380331427
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
  rhythmicContrast: 0.6565139633603394
typography_spectrum: 0.5784543862100691
layout_spectrum: 0.7543841041624546
name: Milan Fine Art Collection
